import java.util.Hashtable;

public class Bank {
	// Set number of max accounts
	private final int MAX_ACCOUNTS = 500;
	//Create hashtable with the size of max accounts
	Hashtable<Integer, User> users = new Hashtable<Integer, User>(MAX_ACCOUNTS);
	
	
// ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER ADDUSER
	// Method that adds users from the hashtable
	public void addUser(User user) {
		users.put(user.getAccount().getAccountNumber(), user);
		
	}
	
	
// REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER REMOVEUSER
	// Method that removes user from hashtable
	public void removeUser(Object key) {
		users.remove(key);
	}
	
	
// GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER GETUSER	
	// Getter that gets user from hashtable
	public User getUser(Object key) {
		return users.get(key);
	}
	
	
// CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY CONTAINSKEY
	// Checks for key in hashtable
	public boolean containsKey(Object test) {
		return users.containsKey(test);
	}
	
	
}